export const INCREASE_CART_PRODUCT_QTY = 'INCREASE_CART_PRODUCT_QTY';
export const UPDATE_PRODUCT_QTY = 'UPDATE_PRODUCT_QTY';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const UPDATE_ORDER_FORM_FIELD = 'UPDATE_ORDER_FORM_FIELD';
export const SET_ORDER_FORM_FIELD_ERROR = 'SET_ORDER_FORM_FIELD_ERROR';
export const CLEAN_STORE = 'CLEAN_STORE';
export const SET_LEAD_SOURCE = 'SET_LEAD_SOURCE';
