export const INCREASE_CART_PRODUCT_QTY = 'INCREASE_CART_PRODUCT_QTY';
export const UPDATE_PRODUCT_QTY = 'UPDATE_PRODUCT_QTY';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
